baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'GoCo Blog'
theme = 'paper'

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  
  [[menu.main]]
  name = "Portfolio"
  url = "/portfolio/"
  weight = 2
  
  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3